accounts/urls.py
from django.urls import path

from accounts import views

app_name = "auth"

urlpatterns = [
    path("signup/", views.UserSignUpView.as_view(), name="signup"), # auth:signup
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="profile"),
]

network/urls.py
from django.urls import path

from network import views

app_name = "network"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("new", views.NewTweetView.as_view(), name="new_tweet"),
    path("delete/<int:pk>", views.DeleteTweetView.as_view(), name="delete"),
    path("tweets", views.AllTweetsView.as_view(), name="tweets"),
    path("following", views.FollowingTweetsView.as_view(), name="following_tweets"),
    path("<str:username>/tweets/<int:tweet_pk>/", views.TweetDetailView.as_view(), name="tweet_detail"),
    path("tweets/<int:tweet_pk>/delete", views.delete_tweet, name="delete_tweet"),
    path("tweets/<int:tweet_pk>/edit", views.edit_tweet, name="edit_tweet"),
    path("tweets/<int:pk>/<str:action>", views.tweet_like, name="tweet_like"),
    path("follow", views.follow, name="follow"),
    path("search/", views.SearchView.as_view(), name="search"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("network.urls"))
]

network/models.py
from django.db import models
from django.urls import reverse

from accounts.models import User

# Create your models here.

class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tweets")
    content = models.TextField(blank=False)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="tweets_liked")

    def __str__(self):
        return f"{self.pk}"
    
    def get_absolute_path(self):
        return reverse("network:tweet_detail", args=(self.user.username, self.pk))

    class Meta:
        ordering = ["-date"]


class Comment(models.Model):
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments_made")
    content = models.TextField(blank=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}: {self.content[:25]}"


class Follow(models.Model):
    user = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE, null=True)
    following_user = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"{self.user} -> {self.following_user}"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'following_user'], name='unique_followers')
        ]

network/forms.py
from django import forms
# from django.utils.translation import gettext_lazy as _

from network.models import Comment, Tweet


class NewTweetForm(forms.ModelForm):
    
    class Meta:
        model = Tweet
        fields = ["content"]

class NewCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ["content"]

network/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView
from django.views.generic.base import View

from accounts.models import User
from network.forms import NewCommentForm, NewTweetForm
from network.models import Follow, Tweet

# Create your views here.

class IndexView(View):
    model = Tweet
    form_class = NewTweetForm
    template_name = "network/index.html"
    
    def get_queryset(self):
        return Tweet.objects.all()[:5]

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context={
            "tweets": self.get_queryset(),
            "form": self.form_class()
        })


class NewTweetView(LoginRequiredMixin, CreateView):
    model = Tweet
    form_class = NewTweetForm
    template_name = "network/new_tweet.html"
    success_url = "/"

    def form_valid(self, form):
        new_tweet = form.save(commit=False)
        new_tweet.user = self.request.user
        new_tweet.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        path = self.request.POST.get("path")
        if path is not None:
            return path
        return "/"
    

class AllTweetsView(ListView):
    model = Tweet
    template_name = "network/all_tweets.html"
    context_object_name = "tweets"
    paginate_by = 5
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = NewTweetForm()
        context["form"] = form
        return context


class FollowingTweetsView(LoginRequiredMixin, ListView):
    model = Tweet
    template_name = "network/following_tweets.html"
    context_object_name = "tweets"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = NewTweetForm()
        context["form"] = form
        return context
    
    def get_queryset(self, **kwargs):
        user = self.request.user
        following_users_ids = user.following.values_list('following_user_id', flat=True)
        posts = Tweet.objects.filter(user__id__in=following_users_ids)

        return posts


class DeleteTweetView(LoginRequiredMixin, DeleteView):
    model = Tweet
    
    def get_success_url(self):
        return self.request.user.get_absolute_path()


def tweet_like(request, pk, action):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)
    
    data = json.loads(request.body)
    try:
        user_liking = User.objects.get(pk=data.get("userLiking"))
    except User.DoesNotExist:
        return JsonResponse({
                "error": f"User {data.get('userLiking')} does not exist."
            }, status=400)
    
    tweet = Tweet.objects.filter(pk=pk).first()
    
    if action == "like":
        tweet.likes.add(user_liking)
    elif action == "unlike":
        tweet.likes.remove(user_liking)
    return JsonResponse({"message": "Ok"}, status=200)


def follow(request):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)
    
    data = json.loads(request.body)
    status = data.get("status")
    request_user = data.get("request_user")
    user_profile = data.get("user_profile")
    try:
        request_user = User.objects.get(pk=request_user)
        user_profile = User.objects.get(pk=user_profile)
    except User.DoesNotExist:
        return JsonResponse({"message": "User does not Exist!"}, status=400)

    if status == "follow":
        Follow.objects.create(user=request_user, following_user=user_profile)
    else:
        request_user.following.get(following_user=user_profile).delete()
        request_user.save()

    return JsonResponse({"message": "Ok"}, status=200)


def delete_tweet(request, tweet_pk):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)
    data = json.loads(request.body)
    request_user_pk = int(data.get("request_user"))
    
    try:
        tweet = Tweet.objects.get(pk=tweet_pk)
    except Tweet.DoesNotExist:
        return JsonResponse({"message": "Tweet does not exist!"}, status=404)

    if tweet.user.pk != request_user_pk:
        return JsonResponse({"message": "User provided is not the tweet owner!"}, status=403)

    tweet.delete()
    return JsonResponse({"message": "Ok"}, status=200)


def edit_tweet(request, tweet_pk):
    if request.method != "PUT":
        return JsonResponse({"error": "PUT request required."}, status=400)
    
    data = json.loads(request.body)
    tweet_owner_pk = data.get("tweet_owner")
    tweet_pk = data.get("tweet_pk")
    new_tweet_content = data.get("new_tweet_content")

    try:
        tweet = Tweet.objects.get(pk=tweet_pk)
    except Tweet.DoesNotExist:
        return JsonResponse({"message": "Tweet does not exist!"}, status=404)

    if tweet.user.pk != tweet_owner_pk:
        print(tweet.user.pk)
        print(tweet_owner_pk)
        return JsonResponse({"message": "User provided is not the tweet owner!"}, status=403)
    
    tweet.content = new_tweet_content
    tweet.save()
    return JsonResponse({"message": "Ok"}, status=200)


class TweetDetailView(View):
    template_name = "network/tweet_detail.html"
    context_object_name = "tweet"
    form_class = NewCommentForm

    def get(self, request, username, tweet_pk, **kwargs):
        form = self.form_class()
        tweet = get_object_or_404(Tweet, pk=tweet_pk)
        comments = tweet.comments.all()
        if tweet.user.username != username:
            return HttpResponseRedirect(reverse("network:index"))
        
        return render(request, self.template_name, context={
            "form": form,
            "tweet": tweet,
            "comments": comments
        }) 

        
    def post(self, request, username, tweet_pk, **kwargs):
        user = request.user
        tweet = get_object_or_404(Tweet, pk=tweet_pk)
        path = request.POST.get("path")
        if user.is_authenticated:
            form = self.form_class(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = user
                comment.tweet = tweet
                comment.save()
            else:
                print(f"Error: {form.errors}")

        return HttpResponseRedirect(path)


class SearchView(ListView):
    model = Tweet
    template_name = "network/all_tweets.html"
    context_object_name = "tweets"
    form_class = NewTweetForm

    def get_queryset(self):
        q = self.request.GET.get("q", "").strip()
        if q:
            return Tweet.objects.filter(content__icontains=q)
        
        return super().get_queryset()
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["form"] = self.form_class()
        return context

network/templates/network/index.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
    <link rel="stylesheet" href="{% static 'network/style.css' %}">
{% endblock style %}

{% block title %} Network {% endblock title %}


{% block content %}
    <div class="container-fluid sans-serif p-4">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-4 col-xl-3 mb-3">
                <div class="card">
                    <div class="card-body">
                        {% if user.is_authenticated %}
                            <div class="row">
                                <div class="col-3 mb-2">
                                    <img src="https://i.stack.imgur.com/l60Hf.png" class="img-fluid img-thumbnail" alt="">
                                </div>
                                <div class="col-8">
                                    <div class="pb-2">
                                        <a href="{{user.get_absolute_path}}"style="text-decoration: none; color: white;">
                                            <h5 class="card-title">{{user.username}}</h5>
                                            <h6 class="card-subtitle mb-2">Profile page</h6>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="status col-4">
                                    <div class="row">
                                        <span style="font-weight: lighter; opacity: 0.65;">Tweets</span>
                                    </div>
                                    <div class="row">
                                        <strong>{{user.tweets.count}}</strong>
                                    </div>
                                </div>
                                <div class="status col-4">
                                    <div class="row">
                                        <span style="font-weight: lighter; opacity: 0.65;">Follwing</span>
                                    </div>
                                    <div class="row">
                                        <strong>{{user.following.count}}</strong>
                                    </div>
                                </div>
                                <div class="status col-4">
                                    <div class="row">
                                        <span style="font-weight: lighter; opacity: 0.65;">Followers</span>
                                    </div>
                                    <div class="row">
                                        <strong>{{user.followers.count}}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="mt-3">
                                <form action="{% url 'network:new_tweet' %}" method="post">
                                    {% csrf_token %}
                                    {% render_field form.content|attr:"autofocus" class+="form-input border border-info form-control mb-2" placeholder="Compose a new Tweet..." rows="1" %}
                                    <button class="btn btn-outline-info btn-sm py-0" type="submit">Tweet &rarr;</button>
                                </form>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="col">
                                    <div class="pb-2">
                                        <h5 class="card-title underline text-center">Login to tweet</h5>
                                        <div class="d-grid col-6 mx-auto mt-4" style="position: relative; top: 3px;">
                                            <a href="{% url 'auth:login' %}" class="btn btn-outline-info btn-sm" type="button">Log In</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <h3 class="card-title text-info text-center"> Most recent Tweets </h3>
                        <hr>
                        <div class="row px-3">
                            <div class="col-lg-12">
                                {% for tweet in tweets %}
                                    <div class="row py-2">
                                            <div class="col-3 col-lg-1 col-md-2 align-self-center">
                                                <a href="{{tweet.user.get_absolute_path}}">
                                                    <img src="https://i.stack.imgur.com/l60Hf.png" class="img-fluid img-thumbnail">
                                                </a>
                                            </div>
                                        <div class="col">
                                            <a href="{% url 'network:tweet_detail' tweet.user.username tweet.pk %}" style="text-decoration: none; color: white;">
                                                <div class="d-flex justify-content-between">
                                                    <strong class="card-author">{{tweet.user.username}}</strong> 
                                                    <small class="card-date">{{tweet.date}}</small>
                                                </div>
                                                <p class="card-text">{{tweet.content | truncatewords:4}} </p>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="row tweet-row ">
                                        <div class="d-flex col px-0 pb-1">
                                            <form action="." method="post" class="likeForm" id="{{tweet.pk}}">
                                                {% csrf_token %}
                                                <input type="hidden" name="tweetID" value="{{tweet.pk}}" id="tweetID-{{tweet.pk}}">
                                                <input type="hidden" name="userLiking" value="{{user.pk}}" id="userLiking-{{tweet.pk}}">
                                                {% if not user.is_authenticated  %}
                                                    <a href="{% url 'auth:login' %}" style="position: relative; top: 2px; padding-right: 3px; padding-left: 4px;"><i class="like bi bi-heart"></i></a>
                                                    <span class="likes-count-guest" id="likes-count-{{tweet.pk}}">{{tweet.likes.count}}</span>
                                                {% else %}
                                                    {% if tweet in user.tweets_liked.all %}
                                                        <button class="submit-icon" type="submit" id="btn-{{tweet.pk}}" value="unlike">
                                                            <i class="liked bi bi-heart-fill"></i>
                                                        </button>
                                                    {% else %}
                                                        <button class="submit-icon" type="submit" id="btn-{{tweet.pk}}" value="like">
                                                            <i class="like bi bi-heart"></i>
                                                        </button>
                                                    {% endif %}
                                                    <span class="likes-count" id="likes-count-{{tweet.pk}}">{{tweet.likes.count}}</span>
                                                {% endif %}
                                            </form>
                                                <a class="submit-icon" href="{{tweet.get_absolute_path}}">
                                                    <i class="comment bi bi-chat"></i>
                                                    <span class="comments-count">{{tweet.comments.count}}</span>
                                                </a>
                                        </div>
                                    </div>
                                    {% empty %}
                                        <div class="row">
                                            <div class="col pt-2">
                                                <p>No tweets yet...</p>
                                            </div>
                                        </div>
                                        
                                {% endfor %}
                                <div class="d-grid gap-2 col-6 mx-auto mt-2" style="position: relative; top: 3px;">
                                    <a href="{% url 'network:tweets' %}" class="btn btn-outline-info btn-sm" type="button">Se all tweets</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}

{% block script %}
    <script src="{% static 'script.js' %}"></script>
{% endblock script %}

network/templates/network/new_tweet.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container-fluid mono p-3">
        <div class="row">
            <h1>New Tweet</h1>
            <div class="col-sm-12 col-md-4">
                <form action="{% url 'network:new_tweet' %}" method="post">
                    {% csrf_token %}
                    {% render_field form.content|attr:"autofocus" class+="form-input border border-info form-control mb-2" placeholder="Compose a new Tweet..." %}
                    <button type="submit" class="btn btn-outline-info mt-2">Tweet</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

network/templates/network/tweet_detail.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
    <!-- <link rel="stylesheet" href="{% static 'accounts/style.css' %}"> -->
    <link rel="stylesheet" href="{% static 'network/style.css' %}">
{% endblock style %}

{% block title %} {{tweet.content}} {% endblock title %}

{% block head_script %}
    <script>
        const tweetOwnerPK = "{{tweet.user.pk}}"
        const tweetPK = "{{tweet.pk}}"
    </script>
{% endblock head_script %}

{% block content %}
{% csrf_token %}
<div class="container sans-serif p-3">
    <div class="row justify-content-center">
        <div class="col-md-9 mt-3 p-3">
            <div class="card p-2">
                <div class="card-body">
                    <div class="row pb-3">
                        <div class="col-3 col-lg-1 col-md-2 align-self-center">
                            <a href="{{tweet.user.get_absolute_path}}">
                                <img src="https://i.stack.imgur.com/l60Hf.png" class="img-fluid img-thumbnail">
                            </a>
                        </div>
                        <div class="col p-0">
                            <h5 class="">@<span class="underline">{{tweet.user.username}}</span></h5>
                        </div>
                        {% if user == tweet.user %}
                            <div class="col pt-2">
                                <div class="d-flex justify-content-end">
                                    <div id="editBtnDiv">
                                        <button class="btn btn-outline-primary btn-sm me-2" id="editBtn" style="border-radius: 0%;">Edit Tweet</button>
                                    </div>
                                    <form action="{% url 'network:delete' tweet.pk %}" method="post">
                                        {% csrf_token %}
                                        <button class="btn btn-outline-danger btn-sm" id="deleteBtn" style="border-radius: 0%;">Delete Tweet</button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="col">
                            <div id="tweetContentDiv">
                                <p class="card-text ps-1" id="tweetContent">{{tweet.content}}</p>
                            </div>
                            <small style="color: grey;">{{tweet.date}}</small>
                        </div>
                    </div>
                    <div class="row p-2">
                        <div class="d-flex col py-1 px-0 tweet-row tweet-row-top">
                            <form action="." method="post" class="likeForm" id="{{tweet.pk}}">
                                {% csrf_token %}
                                <input type="hidden" name="tweetID" value="{{tweet.pk}}" id="tweetID-{{tweet.pk}}">
                                <input type="hidden" name="userLiking" value="{{user.pk}}" id="userLiking-{{tweet.pk}}">
                                {% if not user.is_authenticated  %}
                                    <a href="{% url 'auth:login' %}" style="position: relative; top: 2px; padding-right: 3px; padding-left: 4px;"><i class="like bi bi-heart"></i></a>
                                    <span class="likes-count-guest" id="likes-count-{{tweet.pk}}">{{tweet.likes.count}}</span>
                                {% else %}
                                    {% if tweet in user.tweets_liked.all %}
                                        <button class="submit-icon" type="submit" id="btn-{{tweet.pk}}" value="unlike">
                                            <i class="liked bi bi-heart-fill"></i>
                                        </button>
                                    {% else %}
                                        <button class="submit-icon" type="submit" id="btn-{{tweet.pk}}" value="like">
                                            <i class="like bi bi-heart"></i>
                                        </button>
                                    {% endif %}
                                    <span class="likes-count" id="likes-count-{{tweet.pk}}">{{tweet.likes.count}}</span>
                                {% endif %}
                            </form>
                            <a class="submit-icon" id="submitIcon">
                                <i class="comment bi bi-chat"></i>
                                <span class="comments-count">{{tweet.comments.count}}</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mt-3 p-2">
                <div class="card-body">
                    {% if user.is_authenticated %}
                        <div class="comment-form" id="comment-section">
                            <form action="." method="post">
                                {% csrf_token %}
                                <input type="hidden" name="path" value="{{request.path}}">
                                <label class="comment-as mb-2" for="{{form.content.id_for_label}}">Comment as <span>{{user.username}}</span></label>
                                {% render_field form.content rows="5" cols="20" class+="border border-info form-control mb-2" %}
                                <button class="btn btn-info btn-sm mb-3" style="border-radius: 0%;">Comment <i style="position: relative; top: 1.5px;" class="bi bi-arrow-right"></i></button>
                                <hr class="hr-style">
                            </form>
                        </div>
                    {% endif %}
                    <div class="all-comments mt-3">
                        {% for comment in comments %}
                            <div class="row">
                                <div class="col-3 col-lg-1 col-md-2 align-self-center">
                                    <a href="{{tweet.user.get_absolute_path}}">
                                        <img src="https://i.stack.imgur.com/l60Hf.png" class="img-fluid img-thumbnail">
                                    </a>
                                </div>
                                <div class="col p-0">
                                    <small class="" style="font-size: 13px;">@<span class="">{{comment.user.username}}</span></small> <br>
                                    <span style="font-size: 13px; position: relative; bottom: 5px; opacity: 0.4;">{{comment.date}}</span>
                                </div>
                            </div>
                            <div class="row">
                                <p style="opacity: 0.75;">{{comment.content}}</p>
                            </div>
                            {% empty %}
                                <div style="opacity: 0.4;">
                                    <h5 class="text-center">No Comments Yet.</h5>
                                    <p class="text-center" style="font-size: 13px;">Be the first to share what you think!</p>
                                    <div class="d-flex justify-content-center">
                                        <i class="comment bi bi-chat" style="position: relative; bottom: 13px; font-size: 2rem;"></i>
                                    </div>
                                </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
    <script>
        document.querySelector("#submitIcon").addEventListener("click", function() {
            document.querySelector("#id_content").focus();
        })
    </script>
    <script src="{% static 'script.js' %}"></script>
    <script src="{% static 'network/script.js' %}"></script>
    <script src="{% static 'accounts/followFeature.js' %}"></script>
    <script src="{% static 'accounts/tweetAction.js' %}"></script>
{% endblock script %}