accounts/urls.py
from django.urls import path

from accounts import views

app_name = "auth"

urlpatterns = [
    path("signup/", views.UserSignUpView.as_view(), name="signup"), # auth:signup
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="profile"),
]

network/urls.py
from django.urls import path

from network import views

app_name = "network"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("new", views.NewTweetView.as_view(), name="new_tweet"),
    path("delete/<int:pk>", views.DeleteTweetView.as_view(), name="delete"),
    path("tweets", views.AllTweetsView.as_view(), name="tweets"),
    path("following", views.FollowingTweetsView.as_view(), name="following_tweets"),
    path("<str:username>/tweets/<int:tweet_pk>/", views.TweetDetailView.as_view(), name="tweet_detail"),
    path("tweets/<int:tweet_pk>/delete", views.delete_tweet, name="delete_tweet"),
    path("tweets/<int:tweet_pk>/edit", views.edit_tweet, name="edit_tweet"),
    path("tweets/<int:pk>/<str:action>", views.tweet_like, name="tweet_like"),
    path("follow", views.follow, name="follow"),
    path("search/", views.SearchView.as_view(), name="search"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("network.urls"))
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{% endblock title %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css" />
        <link rel="stylesheet" href="{% static 'style.css' %}" />
        {% block style %} {% endblock style %}
        {% block head_script %} {% endblock head_script %}
    </head>

    <body>
        <header>
            <nav id="idNavbar" class="navbar navbar-expand-lg">
                <div class="sans-serif container-fluid">
                    <a class="navbar-brand text-info" href="{% url 'network:index' %}">TwT</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav" style="position: relative; top: 3px;">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'network:new_tweet' %}">New Tweet</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'network:tweets' %}">Tweets</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'network:following_tweets' %}">Following</a>
                            </li>
                        </ul>
                        <form action="{% url 'network:search' %}" method="get" class="d-flex mx-auto my-2" role="search">
                            <input class="form-control me-2" name="q" type="search" placeholder="Search"
                                aria-label="Search" />
                            <button class="btn btn-outline-info" type="submit">
                                Search
                            </button>
                        </form>
                        <ul class="navbar-nav" style="position: relative; top: 4px;">
                            {% if user.is_authenticated %}
                                <li class="nav-item pe-3">
                                    <a class="underline nav-link" aria-current="page" href="{{user.get_absolute_path}}">{{user.username}}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-outline-info" aria-current="page" href="{% url 'auth:logout' %}">Logout</a>
                                </li>
                            {% else %}
                                <li class="nav-item pe-3 mb-2">
                                    <a class="btn btn-outline-info" aria-current="page" href="{% url 'auth:login' %}">Log In</a>
                                </li>
                                <li class="nav-item pe-2">
                                    <a class="btn btn-info" aria-current="page" href="{% url 'auth:signup' %}">Sign Up</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
        {% block script %}
        {% endblock script %}
    </body>

</html>